### PR TITLE
Fix naming of storage

### PR DESCRIPTION
**Pull request by CatStudioApp**
underscore case is more commonly used by ruby

### CODE REVIEW

**Review by codespearhead — APPROVED** [review]

**Comment by codespearhead** [comment]
[For reference](https://namingconvention.org/ruby/method-naming): 
> - Should be all in lowercase
> - Preferably a verb e.g. get_car(), purchase(), book()
> - **If the name contains multiple words, it should be separated by underscores (_) e.g. get_json()**
> - Clear and descriptive method names without abbreviations are preferred.

**Review by xiaoyijun — APPROVED** [review]
LGTM

**Comment by xiaoyijun** [comment]
Hi @CatStudioApp , thanks for your contribution, however, the base branch requires all commits to be signed. Could you please update your commits?
image

**Comment by xiaoyijun** [comment]
Failed to update this PR since it's on the master branch. Create a new PR to resolved this isse: https://github.com/logto-io/ruby/pull/18

**Pull request closed without merging**
